# Feature Engineering and Model Preparation

Following exploratory analysis, the dataset is prepared for machine learning modeling. 
This stage involves removing redundant variables, selecting relevant features, and splitting the dataset into training and testing sets.

Proper feature preparation ensures the model learns meaningful patterns without unnecessary complexity.

## Importing Required Libraries

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv("cleaned_churn_dataset.csv")
df.head()

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,customer_service_calls,churn
0,KS,128,415,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,0
1,OH,107,415,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,0
2,NJ,137,415,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,0
3,OH,84,408,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,0
4,OK,75,415,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,0

## Removing Redundant Features

Exploratory analysis revealed that call charges are perfectly correlated with their corresponding usage minutes. 
To avoid redundancy and reduce feature multicollinearity, charge columns are removed.

In [5]:
df = df.drop(columns = [
    "total_day_charge",
    "total_eve_charge",
    "total_night_charge",
    "total_intl_charge"
])
df.head()

,state,account_length,area_code,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_eve_minutes,total_eve_calls,total_night_minutes,total_night_calls,total_intl_minutes,total_intl_calls,customer_service_calls,churn
0,KS,128,415,0,1,25,265.1,110,197.4,99,244.7,91,10.0,3,1,0
1,OH,107,415,0,1,26,161.6,123,195.5,103,254.4,103,13.7,3,1,0
2,NJ,137,415,0,0,0,243.4,114,121.2,110,162.6,104,12.2,5,0,0
3,OH,84,408,1,0,0,299.4,71,61.9,88,196.9,89,6.6,7,2,0
4,OK,75,415,1,0,0,166.7,113,148.3,122,186.9,121,10.1,3,3,0

## Removing Non-Predictive Features

Certain features such as geographic state identifiers and area codes are unlikely to provide meaningful predictive signals for churn and may introduce unnecessary complexity. 
These features are therefore removed.

In [6]:
df = df.drop(columns=["state", "area_code"])

## Defining Features and Target Variable

The dataset is separated into predictor variables (features) and the target variable (churn).

In [7]:
X = df.drop("churn", axis=1)
y = df["churn"]

## Splitting Training and Testing Data

The dataset is divided into training and testing subsets. 
The training set is used to train machine learning models, while the testing set evaluates model performance on unseen data.

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

## Training and Testing Dataset Dimensions
Verification of training and testing dataset's dimensions need to be done for unbiased evaluation.

In [9]:
print("Training features:", X_train.shape)
print("Testing features:", X_test.shape)

print("Training labels:", y_train.shape)
print("Testing labels:", y_test.shape)

Training features: (2666, 13)
Testing features: (667, 13)
Training labels: (2666,)
Testing labels: (667,)